// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RedDog.Messenger")]
[assembly: AssemblyDescriptionAttribute("A set helpers and tools for the Microsoft Azure platform.")]
[assembly: AssemblyProductAttribute("Red Dog")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.0";
    }
}
