// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RedDog.Messenger")]
[assembly: AssemblyDescriptionAttribute("A set helpers and tools for the Microsoft Azure platform.")]
[assembly: AssemblyProductAttribute("Red Dog")]
[assembly: AssemblyVersionAttribute("0.5.0.3")]
[assembly: AssemblyFileVersionAttribute("0.5.0.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.0.3";
    }
}
