// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RedDog.ServiceBus")]
[assembly: AssemblyDescriptionAttribute("Helpers for Microsoft Azure Service Bus")]
[assembly: AssemblyProductAttribute("Red Dog for Microsoft Azure")]
[assembly: AssemblyVersionAttribute("1.2.3.4")]
[assembly: AssemblyFileVersionAttribute("1.2.3.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.2.3.4";
    }
}
